name: Pyapp
 
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
 
jobs:
  build:
   runs-on: ubuntu-latest
 
   steps:
    - name: Checkout
      uses: actions/checkout@v2
 
    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.2
 
    - name: Instalando dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
 
    - name: Testes
      run: |
        coverage run -m app_test
 
    - name: Resultados
      run: coverage report
      
    - uses: actions/checkout@v3
      name: Check out code
      
    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      
      with:
       image: repo/image
       tags: v1, latest
       registry: registry-url.io
       dockerfile: Dockerfile.ci
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}
